[project]
name = "pet-first-aid-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pavla Pintaric", email = "pavla.pintaric235@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "lxml>=6.1.2",
    "numpy>=2.5.2",
    "onnxruntime>=1.29.0",
    "openai>=3.6.0",
    "pandas>=3.0.5",
    "psycopg[binary]>=3.2,<4",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
    "requests>=2.34.2",
    "tokenizers>=0.23.1",
    "tqdm>=4.70.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
pet-first-aid-assistant = "pet_first_aid_assistant:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "huggingface-hub>=1.29.0",
    "ipykernel>=7.3.0",
]
